"""
CertStore — On-Disk Device Credential Storage.

Phase 5 Section B. Owns the three files that make up this device's issued
identity, all under a single mounted-volume directory
(config.get_cert_store_path()):
  device.key  -- the private key generated by device_identity.py (NEVER in
                 an image layer -- see that module's docstring)
  device.crt  -- the short-lived certificate issued by the control plane
  ca.crt      -- the control plane's CA chain, used to verify the control
                 plane's server certificate on subsequent mTLS connections

ISO 14971 HAZARD-STREAM-011 (PROPOSED -- pending human security/risk-
management sign-off; new hazard for new code):
  A decommissioned or compromised edge appliance must be revocable --
  otherwise its device certificate (and whatever clinical data access it
  grants) remains valid for as long as the certificate's stated lifetime,
  regardless of the operator's intent to cut it off. Two complementary
  mechanisms are used:
    - Short-lived certificates: the control plane is expected to issue
      certificates with a bounded lifetime (this module enforces nothing
      about that lifetime itself -- it is a control-plane policy decision
      reflected in the certificate's notAfter field, which
      has_valid_identity() below reads and respects).
    - Periodic re-attestation: enrollment_client.py's reattest() is called
      on an interval; a 401/403 response is treated as revocation, and
      quarantine() below is called to make the device certificate
      unusable, forcing a fresh enrollment (with a fresh single-use token
      -- a revoked device cannot silently re-provision itself with the
      same trust). UPDATE: this interval check is now actually SCHEDULED
      -- see infrastructure/provisioning/reattestation.py's
      reattestation_loop(), started as a background task in main.py's
      ASGI lifespan when PROVISIONING_ENABLED=true. Previously reattest()
      was implemented but never called from anywhere in this codebase;
      that gap is now closed. The hazard itself remains PROPOSED (not
      self-closed) -- this update narrows it, it does not resolve it; the
      two gaps below are unchanged by this update.
  NOT implemented here: CRL/OCSP checking against the control plane's CA.
  Re-attestation is the sole revocation signal in this pass, and two gaps
  remain even now that it is actually scheduled:
    - Mid-session gap: an already-open mTLS connection/session is not torn
      down when a revocation is discovered -- only the NEXT reattest()
      tick acts on it. A device revoked between ticks keeps whatever
      session it already has open until that session ends on its own.
    - Network-partition gap: a device that is revoked but
      network-partitioned from the control plane (so it can never
      complete a reattest() call) is NOT mitigated by this design and
      keeps operating on its last-known-valid certificate until it
      expires naturally.
  Flagged for human review: a deployment with a stronger fail-closed
  requirement (e.g. "stop operating if re-attestation has not succeeded in
  N hours, even without an explicit revocation signal", or "terminate open
  sessions immediately on a revoked reattest() result") is not implemented
  in this pass.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from datetime import datetime, timezone

import structlog
from cryptography import x509
from cryptography.hazmat.primitives.asymmetric import ec

from infrastructure.provisioning.device_identity import (
    generate_private_key,
    load_private_key,
    write_private_key_file,
)

_log: structlog.BoundLogger = structlog.get_logger(__name__)

_KEY_FILENAME = "device.key"
_CERT_FILENAME = "device.crt"
_CA_FILENAME = "ca.crt"
_QUARANTINE_SUFFIX = ".revoked"


@dataclass(frozen=True)
class IssuedCredentials:
    """What the control plane returns on successful enrollment."""

    certificate_pem: bytes
    ca_chain_pem: bytes


class CertStore:
    """Reads/writes the device's key + issued certificate + CA chain under
    a single directory. Deliberately does NOT create that directory's
    parent with broad permissions -- callers are expected to mount a
    volume with appropriate ownership (see deploy/k3s/edge-appliance.yaml);
    this class only manages the files inside it."""

    def __init__(self, base_dir: str) -> None:
        self._base_dir = base_dir

    @property
    def key_path(self) -> str:
        return f"{self._base_dir}/{_KEY_FILENAME}"

    @property
    def cert_path(self) -> str:
        return f"{self._base_dir}/{_CERT_FILENAME}"

    @property
    def ca_path(self) -> str:
        return f"{self._base_dir}/{_CA_FILENAME}"

    def load_or_generate_key(self) -> ec.EllipticCurvePrivateKey:
        """Load the persisted key if present; otherwise generate a new one
        and persist it immediately (so a crash right after generation
        doesn't silently lose it -- the CSR built from it would otherwise
        reference a key nobody can find again)."""
        if os.path.exists(self.key_path):
            with open(self.key_path, "rb") as fh:
                return load_private_key(fh.read())

        key = generate_private_key()
        write_private_key_file(self.key_path, key)
        _log.info("provisioning.cert_store.key_generated", path=self.key_path)
        return key

    def write_issued_credentials(self, credentials: IssuedCredentials) -> None:
        os.makedirs(self._base_dir, exist_ok=True)
        with open(self.cert_path, "wb") as fh:
            fh.write(credentials.certificate_pem)
        with open(self.ca_path, "wb") as fh:
            fh.write(credentials.ca_chain_pem)
        _log.info(
            "provisioning.cert_store.credentials_written",
            cert_path=self.cert_path,
            ca_path=self.ca_path,
        )

    def load_certificate(self) -> x509.Certificate | None:
        if not os.path.exists(self.cert_path):
            return None
        with open(self.cert_path, "rb") as fh:
            return x509.load_pem_x509_certificate(fh.read())

    def has_valid_identity(self, *, now: datetime | None = None) -> bool:
        """True iff a private key AND an unexpired, non-quarantined
        certificate are both present. `now` is injectable for testing;
        defaults to the real current UTC time."""
        if not os.path.exists(self.key_path):
            return False
        cert = self.load_certificate()
        if cert is None:
            return False
        current = now or datetime.now(timezone.utc)
        not_after = cert.not_valid_after_utc
        not_before = cert.not_valid_before_utc
        return not_before <= current < not_after

    def quarantine(self) -> None:
        """
        Revocation response: rename the certificate aside so
        has_valid_identity() becomes False and re-enrollment is required.

        Deliberately does NOT delete the private key -- the same key can
        be reused for a fresh CSR on re-enrollment (only the CERTIFICATE
        was revoked; the device's private key was not necessarily
        compromised just because the control plane withdrew trust, e.g. in
        a routine decommission). An operator who suspects key compromise
        should wipe the whole cert_store directory instead, which forces
        both a new key and a new certificate.
        """
        if os.path.exists(self.cert_path):
            os.replace(self.cert_path, self.cert_path + _QUARANTINE_SUFFIX)
        _log.warning(
            "provisioning.cert_store.quarantined",
            cert_path=self.cert_path,
            reason="revocation_signal_from_control_plane",
        )
