variable "name_prefix" {
  type = string
}

variable "ca_certificate_pem" {
  description = "modules/ca's root certificate PEM (fetched from step_ca_endpoint's /roots.pem -- see modules/ca/outputs.tf; Terraform cannot compute this value itself, it must be passed in after a fetch step, e.g. via a data \"http\" source or an operator pasting the output of `curl https://<step_ca_endpoint>/roots.pem`)."
  type        = string
}

variable "ca_certificate_registration_config" {
  description = "AWS IoT Core CA registration requires proof-of-possession of the CA's private key via a verification certificate signed with a CA-provided registration code. This is a manual/scripted bootstrap step against the running step-ca instance (same category of gap as provisioning-api's provisioner JWK -- see DESIGN.md §4), NOT generated by this module. Set this to the resulting verification_certificate_pem once that step has been done."
  type        = string
}

variable "kinesis_shard_count" {
  description = "Start at 1 -- this project's fleet scale (see DESIGN.md §2's CA cost table reasoning) does not need more; Kinesis auto-scaling or on-demand mode should be revisited before this needs manual shard management."
  type        = number
  default     = 1
}
